encoder:
    in_channels: 1
    resolution: 28
    channels: 32
    channels_multipliers: [1, 2, ]
    z_channels: 4
    num_res_blocks: 1
    dropout: 0.0
    
decoder:
    in_channels: 1
    out_channels: 1
    resolution: 28
    channels: 32
    channels_multipliers: [1, 2, ]
    z_channels: 8
    num_res_blocks: 1
    dropout: 0.0

    
