encoder:
    in_channels: 3
    resolution: 512
    channels: 64
    channels_multipliers: [1, 2, 4, 8]
    z_channels: 3
    num_res_blocks: 2
    dropout: 0.0
    
decoder:
    in_channels: 3
    out_channels: 3
    resolution: 512
    channels: 64
    channels_multipliers: [1, 2, 4, 8]
    z_channels: 6
    num_res_blocks: 2
    dropout: 0.0

    
