encoder:
    in_channels: 3
    resolution: 32
    channels: 128
    channel_multipliers: [1, 2,]
    z_channels: 3
    num_res_blocks: 2
    dropout: 0.0
    
decoder:
    in_channels: 3
    out_channels: 3
    resolution: 32
    channels: 128
    channel_multipliers: [1, 2,]
    z_channels: 6
    num_res_blocks: 2
    dropout: 0.0

vae:
    embed_dim: 3
    kld_weight: 1e-6

sampler:
    beta: 'linear'
    T: 1000
    sampling_T: 50
    eta: 1

cond_encoder:
    cond_type : 'class'
    num_cond : 10
    embed_dim : 4

unet:
    dim: 64
    cond_dim : 256