encoder:
    in_channels: 3
    resolution: 256
    channels: 128
    channel_multipliers: [1, 2, 4]
    z_channels: 3
    num_res_blocks: 2
    dropout: 0.0
    
decoder:
    in_channels: 3
    out_channels: 3
    resolution: 256
    channels: 128
    channel_multipliers: [1, 2, 4]
    z_channels: 6
    num_res_blocks: 2
    dropout: 0.0

vae:
    embed_dim: 3
    kld_weight: 1e-6

sampler:
    beta: 'sigmoid'
    T: 1000
    sampling_T: 50
    eta: 1

cond_encoder:
    embed_dim: 512
    cond_dim: 384

unet:
    dim: 192
    dim_mults: [1, 2, 4, 8]
    cond_dim: 384
